import type { UiLocale } from "@/types";

export function topBarStrings(locale: UiLocale) {
  if (locale === "pt") {
    return {
      noConversations: "Ainda sem conversas",
      newConversation: "Nova conversa",
      editorChat: "Editor / Chat",
      templates: "Modelos",
      themes: "Temas",
      conversations: "Conversas",
      tools: "Ferramentas",
      markdownToPdf: "Markdown para PDF",
      renderUml: "Renderizar UML",
      latexTectonic: "LaTeX (Tectonic)",
      saved: "Guardado",
      unsaved: "Alterações por guardar",
      toggleTheme: "Alternar tema",
      applyPatch: "Aplicar patch",
      languageSelect: "Idioma da interface",
      projectPickerLabel: "Selecionar projeto",
      selectWorkspace: "Selecionar workspace",
      workspaces: "Espaços de trabalho",
      configuration: "Configuração",
      integrations: "Integrações",
      settings: "Definições",
      workspaceEditor: "Editor / Chat",
      workspaceEditorDesc: "Abrir o espaço de trabalho ativo",
      latexWorkspaces: "Espaços LaTeX",
      latexWorkspacesDesc: "Documentos técnicos e projetos LaTeX",
      systemDesignWorkspaces: "Espaços de design de sistema",
      systemDesignWorkspacesDesc: "Contexto de sistema e diagramas PlantUML",
      vaultWorkspaces: "Cofres de conhecimento",
      vaultWorkspacesDesc: "Vaults Obsidian para RAG",
      allWorkspaces: "Todos os espaços",
      newProject: "Novo projeto",
      appearance: "Aparência",
      uiThemes: "Temas da interface",
      manageThemes: "Gerir temas…",
      selectColorTheme: "Selecionar tema de cores",
      lightTheme: "Tema claro",
      darkTheme: "Tema escuro",
      language: "Idioma",
      skills: "Competências",
      vaultSkills: "Competências para cofres",
      vaultSkillsSubtitle: "Competências aplicáveis durante a utilização de cofres de conhecimento.",
      dailyReports: "Relatórios diários",
    };
  }
  return {
    noConversations: "No conversations yet",
    newConversation: "New conversation",
    editorChat: "Editor/Chat",
    templates: "Templates",
    themes: "Themes",
    conversations: "Conversations",
    tools: "Tools",
    markdownToPdf: "Markdown to PDF",
    renderUml: "Render UML",
    latexTectonic: "LaTeX (Tectonic)",
    saved: "Saved",
    unsaved: "Unsaved changes",
    toggleTheme: "Toggle theme",
    applyPatch: "Apply Patch",
    languageSelect: "Interface language",
    projectPickerLabel: "Select project",
    selectWorkspace: "Select workspace",
    workspaces: "Workspaces",
    configuration: "Configuration",
    integrations: "Integrations",
    settings: "Settings",
    workspaceEditor: "Editor / Chat",
    workspaceEditorDesc: "Open the active workspace",
    latexWorkspaces: "LaTeX workspaces",
    latexWorkspacesDesc: "Technical documents and LaTeX projects",
    systemDesignWorkspaces: "System design workspaces",
    systemDesignWorkspacesDesc: "System context and PlantUML diagrams",
    vaultWorkspaces: "Knowledge vaults",
    vaultWorkspacesDesc: "Obsidian vaults for RAG",
    allWorkspaces: "All workspaces",
    newProject: "New project",
    appearance: "Appearance",
    uiThemes: "UI themes",
    manageThemes: "Manage themes…",
    selectColorTheme: "Select color theme",
    lightTheme: "Light theme",
    darkTheme: "Dark theme",
    language: "Language",
    skills: "Skills",
    vaultSkills: "Vault skills",
    vaultSkillsSubtitle: "Skills applied during knowledge vault consumption.",
    dailyReports: "Daily reports",
  };
}

export function dailyReportStrings(locale: UiLocale) {
  if (locale === "pt") {
    return {
      title: "Relatórios diários",
      subtitle: "Descreva o seu dia e a IA estrutura horas, tarefas e categorias.",
      calendar: "Calendário",
      summary: "Resumo do dia",
      chat: "Conversa",
      settings: "Definições",
      save: "Guardar",
      saving: "A guardar…",
      saved: "Guardado",
      unsaved: "Alterações por guardar",
      addEntry: "Adicionar entrada",
      removeEntry: "Remover",
      hours: "Horas",
      description: "Descrição",
      category: "Categoria",
      taskType: "Tipo de tarefa",
      totalHours: "Total",
      narrative: "Visão geral",
      noEntries: "Ainda sem entradas. Descreva o dia no chat ou adicione manualmente.",
      placeholder: "Descreva o que fez hoje…",
      electronRequired: "Relatórios diários requerem a app Electron.",
      parseError: "Resposta da IA com IDs inválidos",
      categories: "Categorias",
      taskTypes: "Tipos de tarefa",
      addCategory: "Adicionar categoria",
      addTaskType: "Adicionar tipo",
      storageRoot: "Pasta de relatórios",
      chooseFolder: "Escolher pasta",
      resetStorage: "Repor predefinição",
      deleteCategoryBlocked: "Categoria em uso em relatórios guardados.",
      deleteTypeBlocked: "Tipo em uso em relatórios guardados.",
      today: "Hoje",
      prevMonth: "Mês anterior",
      nextMonth: "Mês seguinte",
      label: "Nome",
      id: "ID",
      selectCategory: "Selecionar categoria",
      selectType: "Selecionar tipo",
      blockPlanTitle: "Plano de blocos",
      blockPlanHint: "Defina quantos blocos e as horas de cada um antes de gerar (ex.: 1 bloco de 2h e 7 de 1h).",
      blockPlanHours: "Horas por bloco",
      blockPlanCount: "Quantidade",
      addBlockSpec: "Adicionar especificação",
      blockPlanTotal: "{count} blocos · {hours}h no total",
      blockPlanEmpty: "Sem plano — a IA estima horas livremente.",
      blockPlanHoursEmpty: "Indique as horas por bloco.",
      blockPlanHoursInvalid: "Horas inválidas — use um número maior que zero (ex.: 1, 1.5, 2).",
      blockPlanCountEmpty: "Indique a quantidade de blocos.",
      blockPlanCountInvalid: "Quantidade inválida — use um número inteiro maior ou igual a 1.",
      blockPlanInvalidSend: "Corrija o plano de blocos antes de enviar a mensagem.",
      timeTrackerTitle: "Registo de tempo",
      timeTrackerDescription: "O que está a fazer",
      timeTrackerDescriptionPlaceholder: "Descreva a tarefa atual…",
      timeTrackerStart: "Iniciar",
      timeTrackerStop: "Parar",
      timeTrackerPause: "Pausar",
      timeTrackerResume: "Retomar",
      timeTrackerRestart: "Reiniciar",
      timeTrackerEditTime: "Editar tempo",
      timeTrackerRunning: "A contar",
      timeTrackerPaused: "Em pausa",
      timeTrackerEditTimeHint: "Duração (H:MM:SS)",
      timeTrackerApplyTime: "Aplicar",
      timeTrackerEditLog: "Editar",
      timeTrackerDeleteLog: "Eliminar",
      timeTrackerSaveLog: "Guardar",
      timeTrackerCancelEdit: "Cancelar",
      timeTrackerStartTime: "Início",
      timeTrackerEndTime: "Fim",
      timeTrackerOnOtherDay: "Temporizador ativo em {date}",
      timeTrackerGoToDay: "Ir para o dia",
      timeTrackerLog: "Histórico de tempo",
      timeTrackerLogEmpty: "Ainda sem sessões registadas hoje.",
      timeTrackerCategoryRequired: "Selecione categoria e tipo, ou deixe ambos vazios.",
      timeTrackerDescriptionRequired: "A descrição é obrigatória.",
      timeTrackerAddToSummary: "Adicionar ao resumo",
      timeTrackerInSummary: "No resumo",
      timeTrackerSummaryHours: "Resumo: {hours}",
    };
  }
  return {
    title: "Daily reports",
    subtitle: "Describe your day and AI structures hours, tasks, and categories.",
    calendar: "Calendar",
    summary: "Day summary",
    chat: "Chat",
    settings: "Settings",
    save: "Save",
    saving: "Saving…",
    saved: "Saved",
    unsaved: "Unsaved changes",
    addEntry: "Add entry",
    removeEntry: "Remove",
    hours: "Hours",
    description: "Description",
    category: "Category",
    taskType: "Task type",
    totalHours: "Total",
    narrative: "Overview",
    noEntries: "No entries yet. Describe your day in chat or add manually.",
    placeholder: "Describe what you did today…",
    electronRequired: "Daily reports require the Electron app.",
    parseError: "AI response used invalid category or task type IDs",
    categories: "Categories",
    taskTypes: "Task types",
    addCategory: "Add category",
    addTaskType: "Add type",
    storageRoot: "Reports folder",
    chooseFolder: "Choose folder",
    resetStorage: "Reset to default",
    deleteCategoryBlocked: "Category is used in saved reports.",
    deleteTypeBlocked: "Task type is used in saved reports.",
    today: "Today",
    prevMonth: "Previous month",
    nextMonth: "Next month",
    label: "Label",
    id: "ID",
    selectCategory: "Select category",
    selectType: "Select type",
    blockPlanTitle: "Block plan",
    blockPlanHint: "Set how many blocks and hours each before generating (e.g. 1 block of 2h and 7 of 1h).",
    blockPlanHours: "Hours per block",
    blockPlanCount: "Count",
    addBlockSpec: "Add specification",
    blockPlanTotal: "{count} blocks · {hours}h total",
    blockPlanEmpty: "No plan — AI estimates hours freely.",
    blockPlanHoursEmpty: "Enter hours per block.",
    blockPlanHoursInvalid: "Invalid hours — use a number greater than zero (e.g. 1, 1.5, 2).",
    blockPlanCountEmpty: "Enter the number of blocks.",
    blockPlanCountInvalid: "Invalid count — use a whole number of at least 1.",
    blockPlanInvalidSend: "Fix the block plan before sending a message.",
    timeTrackerTitle: "Time tracker",
    timeTrackerDescription: "What you're doing",
    timeTrackerDescriptionPlaceholder: "Describe the current task…",
    timeTrackerStart: "Start",
    timeTrackerStop: "Stop",
    timeTrackerPause: "Pause",
    timeTrackerResume: "Resume",
    timeTrackerRestart: "Restart",
    timeTrackerEditTime: "Edit time",
    timeTrackerRunning: "Running",
    timeTrackerPaused: "Paused",
    timeTrackerEditTimeHint: "Duration (H:MM:SS)",
    timeTrackerApplyTime: "Apply",
    timeTrackerEditLog: "Edit",
    timeTrackerDeleteLog: "Delete",
    timeTrackerSaveLog: "Save",
    timeTrackerCancelEdit: "Cancel",
    timeTrackerStartTime: "Start",
    timeTrackerEndTime: "End",
    timeTrackerOnOtherDay: "Timer running on {date}",
    timeTrackerGoToDay: "Go to day",
    timeTrackerLog: "Time log",
    timeTrackerLogEmpty: "No tracked sessions yet today.",
    timeTrackerCategoryRequired: "Select both category and task type, or leave both empty.",
    timeTrackerDescriptionRequired: "Description is required.",
    timeTrackerAddToSummary: "Add to summary",
    timeTrackerInSummary: "In summary",
    timeTrackerSummaryHours: "Summary: {hours}",
  };
}

export function conversationsListStrings(locale: UiLocale) {
  if (locale === "pt") {
    return {
      title: "Espaços de trabalho",
      subtitle: "Selecione um espaço para abrir no editor/chat.",
      empty: "Ainda sem espaços de trabalho. Crie um a partir da tela inicial.",
      filteredEmpty: "Ainda sem espaços de trabalho do tipo {kind}.",
      activeLabel: "Ativo",
    };
  }
  return {
    title: "Workspaces",
    subtitle: "Select a workspace to open in the editor/chat.",
    empty: "No workspaces yet. Create one from the home screen.",
    filteredEmpty: "No {kind} workspaces yet.",
    activeLabel: "Active",
  };
}

export function skillsStrings(locale: UiLocale) {
  if (locale === "pt") {
    return {
      skills: "Competências",
      vaultSkills: "Competências para cofres",
      vaultSkillsTitle: "Competências para cofres",
      vaultSkillsSubtitle: "Competências pré-definidas aplicáveis durante a utilização de cofres de conhecimento.",
      vaultSkillsList: "Competências",
      newSkill: "Nova competência",
      deleteSkill: "Eliminar",
      saveSkill: "Guardar",
      saving: "A guardar…",
      builtinBadge: "Integrada",
      customBadge: "Personalizada",
      readOnlyHint: "Integrada — só leitura",
      skillName: "Nome",
      skillDescription: "Descrição",
      skillMarkdown: "Markdown",
      skillPreview: "Pré-visualização",
      emptySkills: "Ainda sem competências.",
      selectSkillHint: "Selecione uma competência da lista.",
      deleteSkillConfirm: "Eliminar esta competência?",
      skillNamePlaceholder: "Nome da competência",
      skillDescriptionPlaceholder: "Breve descrição",
    };
  }
  return {
    skills: "Skills",
    vaultSkills: "Vault skills",
    vaultSkillsTitle: "Vault skills",
    vaultSkillsSubtitle: "Pre-built skills applied during knowledge vault consumption.",
    vaultSkillsList: "Skills",
    newSkill: "New skill",
    deleteSkill: "Delete",
    saveSkill: "Save",
    saving: "Saving…",
    builtinBadge: "Built-in",
    customBadge: "Custom",
    readOnlyHint: "Built-in — read only",
    skillName: "Name",
    skillDescription: "Description",
    skillMarkdown: "Markdown",
    skillPreview: "Preview",
    emptySkills: "No skills yet.",
    selectSkillHint: "Select a skill from the list.",
    deleteSkillConfirm: "Delete this skill?",
    skillNamePlaceholder: "Skill name",
    skillDescriptionPlaceholder: "Short description",
  };
}

export function settingsStrings(locale: UiLocale) {
  if (locale === "pt") {
    return {
      pageTitle: "Definições",
      pageSubtitle: "Preferências da aplicação e ferramentas.",
      navGeneral: "Geral",
      navSystemPrompts: "Prompts do sistema",
      navSystemDesign: "Design de sistema",
      navLatex: "LaTeX",
      navVault: "Cofre",
      navMarkdownPdf: "Markdown para PDF",
      navUmlRender: "Renderizar UML",
      navLatexTectonic: "Renderizar LaTeX",
      navDailyReports: "Relatórios diários",
      transcriptionModel: "Modelo de transcrição",
      transcriptionModelDesc:
        "Modelo Whisper local usado pela entrada por voz no chat. A primeira utilização pode transferir pesos para disco.",
      transcriptionElectronNote: "A entrada por voz requer a app desktop Electron.",
      placeholderTitle: "Definições em breve",
      placeholderBody: "As definições específicas desta ferramenta serão adicionadas aqui.",
      systemDesignNote:
        "Pastas e referências por espaço de trabalho continuam disponíveis no modal de definições do chat.",
      systemPromptsDescription:
        "Overrides globais aplicados a todos os espaços de trabalho antes dos overrides específicos de cada workspace.",
      systemPromptsGlobalNote:
        "A ordem de resolução é: default, override global e override da workspace. Se um override global de prompt completo estiver ativo, segmentos da workspace não são aplicados; use um prompt completo na workspace ou desative o global.",
      speechModelTiny: "Tiny (~40 MB, mais rápido)",
      speechModelBase: "Base (~75 MB, predefinido)",
      speechModelSmall: "Small (~150 MB, boa qualidade)",
      speechModelMedium: "Medium (~750 MB, melhor qualidade, muita RAM)",
    };
  }
  return {
    pageTitle: "Settings",
    pageSubtitle: "Application and tool preferences.",
    navGeneral: "General",
    navSystemPrompts: "System prompts",
    navSystemDesign: "System design",
    navLatex: "LaTeX",
    navVault: "Vault",
    navMarkdownPdf: "Markdown to PDF",
    navUmlRender: "Render UML",
    navLatexTectonic: "Render LaTeX",
    navDailyReports: "Daily reports",
    transcriptionModel: "Transcription model",
    transcriptionModelDesc:
      "Local Whisper model used by voice input in chat. First use may download weights to disk.",
    transcriptionElectronNote: "Voice input requires the Electron desktop app.",
    placeholderTitle: "Settings coming soon",
    placeholderBody: "Tool-specific settings for this section will be added here.",
    systemDesignNote:
      "Per-workspace folders and references remain available from the chat settings modal.",
    systemPromptsDescription:
      "Global overrides applied to every workspace before workspace-specific overrides.",
    systemPromptsGlobalNote:
      "Resolution order is: default, global override, then workspace override. If a global full-prompt override is active, workspace segment overrides are not applied; use a workspace full prompt or disable the global override.",
    speechModelTiny: "Tiny (~40 MB, fastest)",
    speechModelBase: "Base (~75 MB, default)",
    speechModelSmall: "Small (~150 MB, good quality)",
    speechModelMedium: "Medium (~750 MB, best quality, heavy RAM)",
  };
}

export function voiceInputStrings(locale: UiLocale) {
  if (locale === "pt") {
    return {
      startVoice: "Iniciar entrada por voz",
      stopVoice: "Parar entrada por voz",
      listening: "A ouvir…",
      transcribing: "A transcrever…",
      unsupported: "A entrada por voz requer a app desktop Electron.",
      micDenied:
        "Acesso ao microfone negado. Ative o microfone nas definições do sistema.",
      modelLoading: "A carregar o modelo de voz Whisper (primeira vez: download para disco)…",
      transcriptionFailed: "Falha na transcrição por voz",
    };
  }
  return {
    startVoice: "Start voice input",
    stopVoice: "Stop voice input",
    listening: "Listening…",
    transcribing: "Transcribing…",
    unsupported: "Voice input requires the Electron desktop app.",
    micDenied: "Microphone access denied. Enable the microphone in system settings.",
    modelLoading: "Loading Whisper speech model (first use downloads weights to disk)…",
    transcriptionFailed: "Voice transcription failed",
  };
}

export const DEFAULT_VAULT_PLAYGROUND_SKILL_ID = "builtin:vault-search";

export function vaultPlaygroundStrings(locale: UiLocale) {
  if (locale === "pt") {
    return {
      openButton: "Testar cofre",
      title: "Playground do cofre",
      subtitle: "Converse com o cofre usando um modelo local e competências de consumo.",
      skillLabel: "Competência",
      builtinSkillSuffix: " (integrada)",
      activeFile: "Ficheiro ativo",
      noActiveFile: "nenhum",
      emptyHint: "Faça perguntas sobre as notas do cofre. Toque num caminho para abrir a nota no editor.",
      clearChat: "Limpar conversa",
      close: "Fechar playground",
      openNote: "Abrir nota",
      electronRequired: "O playground requer a app Electron com IA local configurada.",
      placeholder: "Pergunte sobre o cofre ou peça para encontrar notas…",
      footerHint: "Respostas usam o modelo local selecionado e a competência escolhida.",
    };
  }
  return {
    openButton: "Test vault",
    title: "Vault playground",
    subtitle: "Converse with your vault using a local model and consumption skills.",
    skillLabel: "Skill",
    builtinSkillSuffix: " (built-in)",
    activeFile: "Active file",
    noActiveFile: "none",
    emptyHint: "Ask questions about vault notes. Click a path below a reply to open it in the editor.",
    clearChat: "Clear chat",
    close: "Close playground",
    openNote: "Open note",
    electronRequired: "The playground requires the Electron app with local AI configured.",
    placeholder: "Ask about the vault or request relevant notes…",
    footerHint: "Replies use the selected local model and consumption skill.",
  };
}

export function integrationsStrings(locale: UiLocale) {
  if (locale === "pt") {
    return {
      title: "Integrações",
      subtitle: "Serviços Docker necessários para PlantUML, LaTeX e integrações futuras.",
      stillNeeded: "Ainda por configurar",
      configured: "Configurado",
      notConfigured: "Não configurado",
      comingSoon: "Em breve",
      required: "Necessário",
      startCommand: "Comando de arranque",
      execute: "Executar",
      checkStatus: "Verificar estado",
      copyCommand: "Copiar comando",
      copied: "Copiado",
      electronRequired: "Executar requer a app desktop Electron.",
      executeFailed: "Falha ao executar",
      executeStarted: "Comando enviado — a verificar estado…",
      checking: "A verificar…",
      lastError: "Último erro",
      openDocs: "Documentação",
      configureCta: "Configurar integrações",
      krokiHint: "O Kroki local não está disponível. Configure PlantUML (Kroki) nas integrações.",
      tectonicHint: "O Tectonic via Docker não está pronto. Configure LaTeX (Tectonic) nas integrações.",
    };
  }
  return {
    title: "Integrations",
    subtitle: "Docker services required for PlantUML, LaTeX, and future connectors.",
    stillNeeded: "Still needed",
    configured: "Configured",
    notConfigured: "Not configured",
    comingSoon: "Coming soon",
    required: "Required",
    startCommand: "Start command",
    execute: "Execute",
    checkStatus: "Check status",
    copyCommand: "Copy command",
    copied: "Copied",
    electronRequired: "Execute requires the Electron desktop app.",
    executeFailed: "Execute failed",
    executeStarted: "Command started — checking status…",
    checking: "Checking…",
    lastError: "Last error",
    openDocs: "Documentation",
    configureCta: "Configure integrations",
    krokiHint: "Local Kroki is unavailable. Set up PlantUML (Kroki) in Integrations.",
    tectonicHint: "Docker Tectonic is not ready. Set up LaTeX (Tectonic) in Integrations.",
  };
}

export function themesStrings(locale: UiLocale) {
  if (locale === "pt") {
    return {
      title: "Temas da interface",
      subtitle: "Escolha um tema predefinido ou crie um personalizado a partir de JSON.",
      builtIn: "Incluído",
      custom: "Personalizado",
      duplicate: "Duplicar como novo",
      delete: "Eliminar",
      exportJson: "Exportar JSON",
      importJson: "Importar JSON",
      save: "Guardar tema",
      saving: "A guardar…",
      selectTheme: "Selecionar tema",
      editorLabel: "JSON do tema",
      newThemeName: "Nome do novo tema",
      duplicatePrompt: "Nome para a cópia do tema",
      duplicateConfirm: "Criar cópia",
      duplicateCancel: "Cancelar",
      duplicating: "A duplicar…",
      duplicateFailed: "Não foi possível duplicar o tema. Reinicie a app desktop se estiver no browser.",
      validationError: "JSON inválido",
      active: "Ativo",
      cannotDeleteBuiltIn: "Temas incluídos não podem ser eliminados.",
      readOnlyBuiltIn: "Só leitura — duplique para editar",
      reservedThemeId: "O id não pode coincidir com um tema incluído (default, nord, etc.).",
      saveFailed: "Falha ao guardar o tema.",
    };
  }
  return {
    title: "UI themes",
    subtitle: "Pick a preset theme or create a custom one from JSON.",
    builtIn: "Built-in",
    custom: "Custom",
    duplicate: "Duplicate as new",
    delete: "Delete",
    exportJson: "Export JSON",
    importJson: "Import JSON",
    save: "Save theme",
    saving: "Saving…",
    selectTheme: "Select theme",
    editorLabel: "Theme JSON",
    newThemeName: "New theme name",
    duplicatePrompt: "Name for the theme copy",
    duplicateConfirm: "Create copy",
    duplicateCancel: "Cancel",
    duplicating: "Duplicating…",
    duplicateFailed: "Could not duplicate the theme. Restart the desktop app if you are in the browser.",
    validationError: "Invalid JSON",
    active: "Active",
    cannotDeleteBuiltIn: "Built-in themes cannot be deleted.",
    readOnlyBuiltIn: "Read-only — duplicate to edit",
    reservedThemeId: 'Theme id cannot match a built-in theme (default, nord, etc.).',
    saveFailed: "Failed to save theme.",
  };
}
