import type { DailyReportTaxonomy } from "./dailyReportTypes.ts";

export const DEFAULT_DAILY_REPORT_TAXONOMY: DailyReportTaxonomy = {
  version: 1,
  categories: [
    { id: "absence", label: "Absence" },
    { id: "administrative", label: "administrative" },
    { id: "code-challenge-guideline", label: "code challenge guideline" },
    { id: "development", label: "development" },
    { id: "documentation", label: "documentation" },
    { id: "hacker-rank", label: "Hacker rank" },
    { id: "idle-time", label: "idle time" },
    { id: "internal-process", label: "internal process" },
    { id: "meetings-client", label: "meetings (client)" },
    { id: "meetings-internal", label: "meetings (internal)" },
    { id: "other", label: "other" },
    { id: "technical-interview", label: "technical interview" },
    { id: "testing", label: "testing" },
    { id: "training-trainee", label: "training (trainee)" },
    { id: "training-trainer", label: "training (trainer)" },
  ],
  taskTypes: [
    { id: "absence-general", categoryId: "absence", label: "General" },
    { id: "administrative-general", categoryId: "administrative", label: "General" },
    { id: "code-challenge-guideline-general", categoryId: "code-challenge-guideline", label: "General" },
    { id: "feature-work", categoryId: "development", label: "Feature work" },
    { id: "bugfix", categoryId: "development", label: "Bug fix" },
    { id: "code-review", categoryId: "development", label: "Code review" },
    { id: "documentation-general", categoryId: "documentation", label: "General" },
    { id: "hacker-rank-general", categoryId: "hacker-rank", label: "General" },
    { id: "idle-time-general", categoryId: "idle-time", label: "General" },
    { id: "internal-process-general", categoryId: "internal-process", label: "General" },
    { id: "meetings-client-general", categoryId: "meetings-client", label: "General" },
    { id: "meetings-internal-general", categoryId: "meetings-internal", label: "General" },
    { id: "other-general", categoryId: "other", label: "General" },
    { id: "technical-interview-general", categoryId: "technical-interview", label: "General" },
    { id: "testing-general", categoryId: "testing", label: "General" },
    { id: "training-trainee-general", categoryId: "training-trainee", label: "General" },
    { id: "training-trainer-general", categoryId: "training-trainer", label: "General" },
  ],
};
